services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=${FLASK_APP}  
      - FLASK_RUN_HOST=${FLASK_RUN_HOST} 
      - DATABASE_URL=${DATABASE_URI}
      - FLASK_ENV=${FLASK_ENV}
    networks:
      - mynetworkpy

  frontend:
    build:
      context: ../ibis-poc-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend-python
    ports:
      - "4200:80"
    depends_on:
      - app
    networks:
      - mynetworkpy

networks:
  mynetworkpy:
    driver: bridge

volumes:
  db_data:
    driver: local
