services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=app.py  
      - FLASK_RUN_HOST=0.0.0.0 
      - DATABASE_URL=sqlite:///quickquid.db
      - FLASK_ENV=production
    networks:
      - mynetworkpy

  frontend:
    build:
      context: ../ibis-poc-frontend
      args:
        - ENV= production
      dockerfile: Dockerfile
    container_name: angular-frontend-python
    ports:
      - "4200:80"
    depends_on:
      - app
    networks:
      - mynetworkpy

networks:
  mynetworkpy:
    driver: bridge

volumes:
  db_data:
    driver: local
