services:
  app:
    build:
      context: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - mynetworkpy

  frontend:
    build:
      context: ../ibis-poc-frontend
      dockerfile: Dockerfile
    container_name: angular-frontend-python
    ports:
      - "${PORT_1}:${PORT_2}"
    depends_on:
      - app
    networks:
      - mynetworkpy

networks:
  mynetworkpy:
    driver: bridge

volumes:
  db_data:
    driver: local
